version: "3"
services:
  node_app:
    build: .
    dockerfile: dockerfile
    image: website:latest
    volumes:
      - ./:/app:ro
      - /app/node_modules
    ports:
        - "3000:3000"
    environment:
      - PORT=3000
 
  
